package com.nomina.modal;
// Generated 04/07/2017 17:52:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClProvincia generated by hbm2java
 */
public class ClProvincia  implements java.io.Serializable {


     private int idProvincia;
     private ClPais clPais;
     private String provincia;
     private String estado;
     private Set clCiudads = new HashSet(0);
     private Set clEmpresases = new HashSet(0);

    public ClProvincia() {
    }

	
    public ClProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public ClProvincia(int idProvincia, ClPais clPais, String provincia, String estado, Set clCiudads, Set clEmpresases) {
       this.idProvincia = idProvincia;
       this.clPais = clPais;
       this.provincia = provincia;
       this.estado = estado;
       this.clCiudads = clCiudads;
       this.clEmpresases = clEmpresases;
    }
   
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public ClPais getClPais() {
        return this.clPais;
    }
    
    public void setClPais(ClPais clPais) {
        this.clPais = clPais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getClCiudads() {
        return this.clCiudads;
    }
    
    public void setClCiudads(Set clCiudads) {
        this.clCiudads = clCiudads;
    }
    public Set getClEmpresases() {
        return this.clEmpresases;
    }
    
    public void setClEmpresases(Set clEmpresases) {
        this.clEmpresases = clEmpresases;
    }




}


