package com.nomina.model;
// Generated 10/07/2017 17:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClCiudad generated by hbm2java
 */
public class ClCiudad  implements java.io.Serializable {


     private int idCiudad;
     private ClProvincia clProvincia;
     private String ciudad;
     private String estado;
     private Set clEmpresases = new HashSet(0);

    public ClCiudad() {
    }

	
    public ClCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public ClCiudad(int idCiudad, ClProvincia clProvincia, String ciudad, String estado, Set clEmpresases) {
       this.idCiudad = idCiudad;
       this.clProvincia = clProvincia;
       this.ciudad = ciudad;
       this.estado = estado;
       this.clEmpresases = clEmpresases;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public ClProvincia getClProvincia() {
        return this.clProvincia;
    }
    
    public void setClProvincia(ClProvincia clProvincia) {
        this.clProvincia = clProvincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getClEmpresases() {
        return this.clEmpresases;
    }
    
    public void setClEmpresases(Set clEmpresases) {
        this.clEmpresases = clEmpresases;
    }




}


