package com.nomina.model;
// Generated 10/07/2017 17:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClPais generated by hbm2java
 */
public class ClPais  implements java.io.Serializable {


     private int idPais;
     private String pais;
     private String codigo;
     private String estado;
     private Set clEmpresases = new HashSet(0);
     private Set clProvincias = new HashSet(0);

    public ClPais() {
    }

	
    public ClPais(int idPais) {
        this.idPais = idPais;
    }
    public ClPais(int idPais, String pais, String codigo, String estado, Set clEmpresases, Set clProvincias) {
       this.idPais = idPais;
       this.pais = pais;
       this.codigo = codigo;
       this.estado = estado;
       this.clEmpresases = clEmpresases;
       this.clProvincias = clProvincias;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getClEmpresases() {
        return this.clEmpresases;
    }
    
    public void setClEmpresases(Set clEmpresases) {
        this.clEmpresases = clEmpresases;
    }
    public Set getClProvincias() {
        return this.clProvincias;
    }
    
    public void setClProvincias(Set clProvincias) {
        this.clProvincias = clProvincias;
    }




}


