package com.nomina.model;
// Generated 10/07/2017 17:16:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClTiposIdentificacion generated by hbm2java
 */
public class ClTiposIdentificacion  implements java.io.Serializable {


     private int idTipoIdentificacion;
     private String tipoIdentificacion;
     private String descripcion;
     private String estado;
     private Set clEmpresases = new HashSet(0);

    public ClTiposIdentificacion() {
    }

	
    public ClTiposIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public ClTiposIdentificacion(int idTipoIdentificacion, String tipoIdentificacion, String descripcion, String estado, Set clEmpresases) {
       this.idTipoIdentificacion = idTipoIdentificacion;
       this.tipoIdentificacion = tipoIdentificacion;
       this.descripcion = descripcion;
       this.estado = estado;
       this.clEmpresases = clEmpresases;
    }
   
    public int getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getClEmpresases() {
        return this.clEmpresases;
    }
    
    public void setClEmpresases(Set clEmpresases) {
        this.clEmpresases = clEmpresases;
    }




}


