package com.nomina.model;
// Generated 10/07/2017 17:16:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcUsers generated by hbm2java
 */
public class LcUsers  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String contrasenia;
     private Date fechaRegistro;
     private String estado;

    public LcUsers() {
    }

	
    public LcUsers(int id) {
        this.id = id;
    }
    public LcUsers(int id, String usuario, String contrasenia, Date fechaRegistro, String estado) {
       this.id = id;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


